// Überleitungen (➜) für die Sprechernotizen, je Folie. Prüft, dass die Reihenfolge noch stimmt.
const T = [
  ['Wer fährt', 'Bevor wir anfangen, eine Zahl, die euch überraschen wird.'],
  ['Jeden Tag', ''],
  ['Jeden Tag', ''],
  ['Das Rätsel', ''],
  ['Bevor es losgeht', ''],
  ['Vorfahrt ist ein Recht', 'Zwei Wörter, die fast alle verwechseln: Vorfahrt und Vorrang.'],
  ['Vorfahrt oder Vorrang', 'Wer hat an einer Kreuzung eigentlich das Sagen? Wir bauen einen Turm.'],
  ['Die Rangfolge', ''],
  ['Die Rangfolge', 'Und jetzt kommt eine Ampel dazu. Was passiert mit den Schildern?'],
  ['Die Rangfolge', 'Jetzt stellt sich ein Polizist auf die Kreuzung.'],
  ['Die Rangfolge', 'Wir fangen ganz unten im Turm an: bei der Grundregel.'],
  ['Rechts vor links', 'Wo gilt diese Grundregel überhaupt?'],
  ['Wo gilt rechts vor links', 'Testen wir das an einer Einmündung. Da liegen die meisten falsch.'],
  ['Die kleine Straße', 'Jetzt seid ihr dran: das Kreuzungs-Duell.'],
  ['Wer fährt zuerst', 'Runde 1, zum Warmwerden.'],
  ['Wer fährt zuerst', 'Runde 2: Jetzt kommt ein drittes Auto dazu.'],
  ['Wer fährt zuerst', 'Runde 3: Jetzt biegt einer ab.'],
  ['Wer fährt zuerst', 'Runde 4, der Klassiker. Vier Autos.'],
  ['Wer fährt zuerst', 'Runde 5 kommt später. Erst: Was mache ich, wenn ich nichts sehe?'],
  ['Hineintasten', 'Jetzt eine Falle, in die jedes Jahr viele tappen.'],
  ['Sieht aus wie eine Straße', 'Schaut genau hin: zwei Autos, beide von rechts.'],
  ['Zwei von rechts', 'Woran erkenne ich den Unterschied? Wir holen die Lupe.'],
  ['Schau auf den Bordstein', 'Wer muss beim Einfahren noch alles warten? Hier die komplette Liste.'],
  ['Wer von hier kommt', 'Ein Fall aus der Liste in Bewegung: raus aus dem verkehrsberuhigten Bereich.'],
  ['Raus aus dem verkehrs', 'Zeit für ein kleines Spiel: Mythos oder Fakt?'],
  ['Stimmt das', 'Kapitel 3: Jetzt regeln Schilder die Vorfahrt.'],
  ['Die Form verrät es', 'Welche Schilder gehören noch dazu? Hier alle auf einen Blick.'],
  ['Vorfahrt haben, Vorfahrt geben', 'Das strengste davon: das Stoppschild. Was heißt hier Anhalten?'],
  ['Stopp heißt Stopp', 'Und was passiert, wenn einer das Schild übersieht?'],
  ['Was passiert dann', 'Kapitel 4: Wenn die Vorfahrtstraße einen Knick macht.'],
  ['Abknickende', 'Drei Regeln, dann klappt jeder Knick.'],
  ['So klappt der Knick', 'Schauen wir uns das in Bewegung an.'],
  ['Dem Knick folgen', 'Und jetzt kommt Runde 5 im Kreuzungs-Duell.'],
  ['Wer fährt zuerst', 'Kapitel 5: der Kreisverkehr.'],
  ['Der Kreis', 'Die Regeln im Kreisverkehr als Frage und Antwort.'],
  ['Kreisverkehr: 6 Fragen', 'Kapitel 6: Jetzt regelt die Ampel.'],
  ['Was die Ampel dir sagt', 'Die schwierigste Farbe ist Gelb. Gas oder Bremse?'],
  ['Gas oder Bremse', 'Und wenn es schon Rot ist? Die 1-Sekunde-Ampel.'],
  ['Die 1-Sekunde-Ampel', 'Grün heißt fahren. Aber was ist, wenn ich links abbiege?'],
  ['Links abbiegen bei Grün', 'Und wenn gegenüber auch einer links abbiegen will?'],
  ['Voreinander abbiegen', 'Rot, aber mit Grünpfeil. Darf ich fahren? Der Grünpfeil-Test.'],
  ['Der Grünpfeil', 'Grünpfeil ist nicht gleich Grünpfeil. Nicht verwechseln!'],
  ['Schild oder Licht', 'Und was, wenn die Ampel ganz ausfällt?'],
  ['Stromausfall', 'Es gibt noch Ampeln über einzelnen Fahrstreifen.'],
  ['Signale über dem Fahrstreifen', 'Ganz oben im Turm fehlt noch einer: die Polizei.'],
  ['Wenn die Polizei regelt', 'Wie lese ich, was der Polizist mir sagt?'],
  ['Lies den Polizisten', 'Jetzt auf der Kreuzung: Wer darf fahren?'],
  ['Wer darf fahren', 'Die Polizei regelt nicht nur, sie hält auch an. So sieht das aus.'],
  ['So hält dich die Polizei an', 'Zurück zum Rätsel vom Anfang. Wer lag richtig?'],
  ['Die Auflösung', 'Was nehmt ihr heute mit? Sechs Sätze.'],
  ['Sechs Sätze für die Kreuzung', 'Und ein letzter Satz, über allem.'],
  ['Vorfahrt wird gewährt', ''],
  ['15 Minuten Pause', 'Nach der Pause: Lektion 6. Wir lernen, die Straße zu lesen.'],
  // ---- Lektion 6 ----
  ['Lesen, was die Straße sagt', 'Zum Wachwerden: der Blitz-Test.'],
  ['Eine Sekunde pro Schild', 'Warum war das so schwer? Weil man Schilder nicht auswendig lernt.'],
  ['Du musst sie nicht auswendig', 'Wie liest man ein Schild? An seiner Form.'],
  ['Die Form verrät', 'Testen wir das: das Sortier-Spiel.'],
  ['Wohin gehört es', 'Schauen wir uns die Gefahrzeichen genauer an.'],
  ['Wo steht es', 'Vier Gefahrzeichen: Was sagen sie, was tust du?'],
  ['Was sagt es', 'Jetzt die runden Schilder: Gebote und Verbote.'],
  ['Du musst. Du darfst nicht', 'Wie lange gilt eigentlich so ein Verbot? Testen wir es auf der Landstraße.'],
  ['Gilt die 70 noch', ''],
  ['So endet ein Streckenverbot', 'Oft hängt unter dem Schild noch ein kleines Zusatzzeichen. Wann gilt es?'],
  ['Wann gilt das', 'Die dritte Form: die Richtzeichen.'],
  ['Hinweise, manchmal mit Pflicht', 'Auch Wegweiser haben ein System: die Farbe.'],
  ['Die Farbe zeigt', 'Nicht nur Schilder sprechen.'],
  ['Auch die Straße spricht', 'Drei Linien, drei Regeln.'],
  ['Darf ich rüber', 'Und was, wenn plötzlich gelbe Linien auftauchen?'],
  ['Weiß oder Gelb', 'An Baustellen stehen noch mehr Helfer: die Verkehrseinrichtungen.'],
  ['Die stummen Helfer', 'Zwei davon schauen wir uns genauer an.'],
  ['Wo lang? Welche Seite', 'Wofür Leitpfosten noch gut sind: eine Nacht im Nebel.'],
  ['', 'Letztes Kapitel: der Bahnübergang.'],
  ['Ein Zug kann nicht ausweichen', 'Woran erkennst du, dass ein Bahnübergang kommt?'],
  ['So kündigt er sich an', 'Jetzt stehst du davor, und die Lichter blinken.'],
  ['Die Schranke', 'Wann genau musst du warten? Die komplette Liste.'],
  ['Wann musst du warten', 'Und wenn die Schranke offen ist, aber dahinter Stau?'],
  ['Schranke offen', 'Und wenn das Auto auf den Gleisen stehen bleibt?'],
  ['Auf den Gleisen', 'Wer trotzdem rüberfährt, zahlt teuer.'],
  ['Was es kostet', 'Jetzt seid ihr dran: Ihr baut selbst ein Rätsel.'],
  ['Ihr baut das Rätsel', 'So baut ihr euer Plakat.'],
  ['4 Schritte zum Plakat', 'Nach den Vorstellungen: Was nehmt ihr heute mit?'],
  ['Sechs Sätze zum Lesen', 'Ein letzter Satz für heute.'],
  ['Wer lesen kann', 'Ende des Abends. Nächstes Mal: Lektion 7 und 8.'],
];
module.exports = function (deck) {
  if (deck.slides.length !== T.length) throw new Error(`Überleitungen: ${T.length} Einträge, aber ${deck.slides.length} Folien`);
  deck.slides.forEach((c, i) => {
    const k = (c.tkey || '') + ' ' + (c.key || '');
    if (!k.replace(/\n/g, ' ').includes(T[i][0])) throw new Error(`Überleitung ${i + 1} passt nicht: „${T[i][0]}“ vs. „${k}“`);
    if (T[i][1]) c.ueber = T[i][1];
  });
};
